apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: echo-grpc-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: echo-grpc
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: External
      external: 
        metric:
          name: custom.googleapis.com|envoy_cluster_upstream_cx_active
        target:
          type: Value
          value: 1